# Generated by Django 5.2.15 on 2026-06-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hours for individual/home tutoring sessions",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eloratetier",
            name="rate_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Used for Individual and Home Tutoring sessions",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="deactivation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="elo_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
